#%RAML 1.0
title: Insurance Quotation-Issuance API
version: 1.0
protocols: [ HTTPS ]
mediaType: application/json

documentation:
  - title: Quotation creation and Issuance API
    content: !include document/documentation.md

uses:
  traits: common/traitslibrary.raml
types:
  travelerdetailsReq: !include schema/travelDetails.raml
  travelerdetailsRes: !include schema/travelDetails.raml

/ping:
  get:
    description: Ping request flow test.
    responses:
      200:
        body:
          application/json:
            example: !include example/pingTest.json
/quotationCreation:
  post:
    is: [traits.goSecure, traits.errorResponses]
    description: create quotation for traveler
    body:
      application/json:
        example: !include example/travelerDetailsRequest.json
        type: travelerdetailsReq
    responses:
        201:
            body:
                application/json:
                    example: !include example/travelDetailsResponse.json

/policyCreation:
  post:
    is: [traits.goSecure, traits.errorResponses]
    description: Create a policy for the customers.
    queryParameters:
      quote_id:
        type: string
        example: "zh-2022-001"
      policyName::
        type : string
        example: "anyPolicyName"
    responses:
      201:
        body:
          application/json:
            example: "policy created sucessfully"
              

                      
  
          
    

